name: AstrateqVision
options:
  bundleIdPrefix: com.astrateq
  deploymentTarget:
    iOS: "17.0"
packages:
  SwiftTasksVision:
    url: https://github.com/paescebu/SwiftTasksVision
    from: 0.10.14
targets:
  AstrateqVision:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        includes:
          - "*.swift"
    info:
      path: Info.plist
    dependencies:
      - package: SwiftTasksVision
        product: MediaPipeTasksVision